site_name: NFLProjections
site_description: Python library for fetching and aggregating NFL projections
site_author: Eric Truett
site_url: https://sansbacon.github.io/nflprojections/

repo_url: https://github.com/sansbacon/nflprojections
repo_name: sansbacon/nflprojections

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Architecture:
    - Overview: architecture/overview.md
    - Functional Architecture: architecture/functional.md
  - API Reference:
    - Fetch: api/fetch.md
    - Parse: api/parse.md
    - Standardize: api/standardize.md
    - Scoring: api/scoring.md
    - Combine: api/combine.md
    - Matching: api/matching.md
    - Sources: api/sources.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Usage: examples/advanced.md
  - Development:
    - Contributing: development/contributing.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sansbacon/nflprojections